repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: end-of-file-fixer      
    - id: requirements-txt-fixer
    - id: check-json
    - id: check-merge-conflict

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      additional_dependencies: ["flake8-bugbear"]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
    - id: mypy
      agrs: ['--ignore-missing-imports']
        
- repo: https://github.com/asottile/pyupgrade
  rev: v1.17.1
  hooks:
    - id: pyupgrade
      args: ['--py3-plus', '--py36-plus']

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: 'v1.5.7'
  hooks:
    - id: autopep8
